baseurl = "https://gforestshade.github.io/kujira/"
languageCode = "en"
title = "Kujira, Civ4 Mod Blog"
author = "gforest_shade"
copyright = "gforest_shade; licenced by [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)"
canonifyurls = true
paginate = 5
hasCJKLanguage = true
publishDir = "docs"

theme = "hugo-bootstrap"

disqusShortname = "kujira"
googleAnalytics = "UA-111798374-1"

[[menu.main]]
    name = "TAGS"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "CATEGORIES"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "categories"
    url = "/categories/"

[[menu.footer]]
    name = "LICENSE"
    weight = -120
    identifier = "license"
    url = "/page/license/"

[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

[blackfriday]
    extensions = ["hardLineBreak"]
    