baseurl = "/kujira/"
languageCode = "en"
title = "Kujira, Civ4 Mod Blog"
author = "gforest_shade"
copyright = "Copyright (c) 2017, gforest_shade; licenced by CC-BY-4.0"
canonifyurls = true
paginate = 5
hasCJKLanguage = true
publishDir = "docs"

theme = "hugo-bootstrap"

disqusShortname = ""
googleAnalytics = ""

[[menu.main]]
    name = "TAGS"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "CATEGORIES"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "categories"
    url = "/categories/"

[[menu.main]]
    name = "ABOUT ME"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "about-me"
    url = "/page/about-me"

[[menu.footer]]
    name = "DISCLAIMER"
    weight = -110
    identifier = "disclaimer"
    url = "/page/disclaimer/"

[[menu.footer]]
    name = "LICENSE"
    weight = -120
    identifier = "license"
    url = "/page/license/"

[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

[blackfriday]
    extensions = ["hardLineBreak"]
    