baseurl = "https://gforestshade.github.io/kujira/"
languageCode = "ja-JP"
title = "Kujira, Civ4 Mod Blog"
description = "このサイトは、Civ4のMOD開発情報を発信していくブログです。"
author = "gforest_shade"
copyright = "gforest_shade; licenced by [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)"
canonifyurls = true
paginate = 20
hasCJKLanguage = true
publishDir = "docs"
preserveTaxonomyNames = "True"

theme = "hugo-bootstrap"

disqusShortname = "kujira"
googleAnalytics = "UA-111798374-1"

[[menu.main]]
    name = "TAGS"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "CATEGORIES"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "categories"
    url = "/categories/"

[[menu.main]]
    name = "LICENSE"
    pre = "<i class='fa fa-file'></i>"
    weight = -100
    identifier = "licence1"
    url = "/page/license/"

[[menu.footer]]
    name = "LICENSE"
    weight = -120
    identifier = "license"
    url = "/page/license/"

[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = false

[[params.banners]]
    name = "kujira_paleblue"
    path = "/banner/kujira_paleblue1024x200.png"
    license = "いらすとや"

[[params.banners]]
    name = "photo_yellow"
    path = "/banner/photo_yellow1_1024x200.jpg"
    license = "['Choice' by Seán Mackey](https://www.flickr.com/photos/132803717@N02/27004253005/) (トリミング) under a [Creative Commons Attribution 2.0](https://creativecommons.org/licenses/by/2.0/deed.ja)."

[[params.banners]]
    name = "photo_pink1"
    path = "/banner/photo_pink1_1024x200.png"
    license = "['I love nature and nature loves me .....' by CLAUDIA DEA](https://www.flickr.com/photos/135366503@N05/31176873090/) (トリミング) under a [Creative Commons Attribution 2.0](https://creativecommons.org/licenses/by/2.0/deed.ja)."

[[params.banners]]
    name = "photo_ice1"
    path = "/banner/photo_ice1_1024x200.jpg"
    license = "['Middlebrun Island' by Superior Hiking](https://www.flickr.com/photos/markbyzewski/13510664124/) (トリミング) under a [Creative Commons Attribution 2.0](https://creativecommons.org/licenses/by/2.0/deed.ja)."

[[params.banners]]
    name = "green"
    path = "/banner/green1024x200.png"

[blackfriday]
    extensions = ["hardLineBreak"]
    